.prettierrc
{
"printWidth": 120,
"singleQuote": true,
"trailingComma": "es5",
"tabWidth": 2,
"arrowParens": "avoid"
}
=> style: Prettier 코드 포맷터 설정파일 추가

package-lock.json, package.json, src/pages/MainPage/MyGroup/GroupItem.tsx, src/pages/MainPage/MyGroup/index.tsx, src/pages/MainPage/MyGroup/style.module.css, src/pages/MainPage/Notice.tsx, src/pages/MainPage/index.tsx
=> refactor: 메인페이지 react-slick -> swiper 교체

.gitignore, package-lock.json, package.json, src/index.css, src/utils/axios.ts
=> feat: 폰트 스타일 변경 및 .env 설정

src/components/layout/Header/UserMenu.jsx, src/reducers/thunkFunctions.js, src/reducers/userSlice.js
createSlice 함수에 비동기적으로 처리하지 않고, 동기적으로 처리하기 위해서 reducers 부분에 리듀서 정의
UserMenu.jsx에서 dispatch(logout())을 하면 useSlice.js로 넘어가서 logout 리듀서 로직으로 상태 변경하고 스토리지 항목 제거
주석 달아놨으니 참고!
=> feat: 로그아웃 기능 구현

src/components/common/Button.jsx, src/pages/CategoryPage/CategoryGroup.jsx, src/pages/CategoryPage/CategoryItem.jsx, src/pages/CategoryPage/index.jsx, src/reducers/thunkFunctions.js, src/reducers/userSlice.js
+@) styles: 버튼 스타일 수정
useState로 카테고리 선택된거 상태를 관리하고, 그 상태값을 thunk로 백에 요청 보냄
프로미스 반환값에 따라 리덕스 상태 설정
db, 리덕스 상태 변경 다 잘 되는거까지 확인했음!
=> feat: useState을 통해 카테고리 상태 설정하고 그 값을 thunk로 백과 통신

src/components/common/CustomModal.jsx, src/components/common/test.css, src/pages/LoginPage/LoginModal.jsx, src/pages/SignInPage/NickName/index.jsx, src/pages/SignInPage/NickName/index.scss
1. 로그인 모달창 transition 적용 및 스타일 수정
2. Link 컴포넌트 사용하면 브라우저에서 사용자에게 환경변수로 관리한 api key 등이 노출될 수 있어 window.location.href를 활용해 uri로 이동
=> fix: 로그인 모달창 스타일 수정 및 소셜 로그인 경로 이동 방법 변경

src/pages/CalendarPage/AddTodo.jsx, src/pages/CalendarPage/index.css, src/pages/CalendarPage/index.jsx
- 선택된 일정 상태값 구현 완료
- 디자인 및 API 기능 구현 필요
=> feat: 캘린더 페이지 구현중

package-lock.json, package.json, src/App.jsx, src/components/ProtectedRoutes.jsx, src/components/common/DropDown.jsx, src/pages/CreateGroupPage/GroupCategory.jsx, src/pages/CreateGroupPage/GroupImage.jsx, src/pages/CreateGroupPage/GroupInfo.jsx, src/pages/CreateGroupPage/GroupTargetTime.jsx, src/pages/CreateGroupPage/index.css, src/pages/CreateGroupPage/index.jsx
디자인은 아직 미완성이고 몇시간으로 설정할지 이런거는 더 추가로 작업해야 함.
일단 이미지 올린거랑 input 작성한거 axios로 백에 전달 후 DB 잘 들어가는거까지 확인해서 pr 올림.
=> feat: 그룹 생성 페이지

src/App.jsx, src/pages/LoginPage/LoginModal.jsx, src/pages/OauthPage/KakaoPage.jsx, src/pages/OauthPage/NaverPage.jsx, src/reducers/thunkFunctions.js, src/utils/redirectUrl.js
=> feat: 네이버 로그인

src/pages/CreateGroupPage/GroupCategory.jsx, src/pages/CreateGroupPage/GroupImage.jsx, src/pages/CreateGroupPage/GroupTargetTime.jsx, src/pages/CreateGroupPage/index.jsx, src/pages/MyGroupPage/index.jsx
=> stlyes: 그룹 생성 페이지

src/pages/CalendarPage/index.jsx
=> feat: todo update 상태값 추가

src/App.jsx, src/pages/ChatPage/index.jsx, src/pages/MainPage/MyGroup/GroupItem.jsx, src/pages/MyGroupPage/index.jsx
group스키마를 room스키마로 동기화 하지 않고, groupId 기준으로 채팅방 생성
=> fix: 이전채팅로그 불러오기

src/pages/TimerPage/index.jsx
- 해당 유저 토탈 시간 뷰 구현 완료
- 새로 고침시 시간 저장 구현 완료
- 그룹 맴버 실시간 구현중
=> feat: 타이머 페이지 기능 구현중

src/pages/ChatPage/index.jsx
sendMessage 소켓이벤트에서 groupId도 같이 emit으로 수정
=> fix: savechat

src/pages/RankingPage/GroupRank/index.jsx, src/pages/RankingPage/UserRank/index.jsx, src/pages/RankingPage/index.jsx, tailwind.config.js
그룹 랭킹 추가
반응형 고려해서 스타일링까지
이미지나 이런거는 추후 예정
=> feat: 랭킹 페이지

src/pages/TimerPage/index.jsx
- start, pause 이벤트 발생시 실시간 구현 완료
- 상대방이 입장 시 상대방 is_running 구현 필요
=> feat: 타이머 구현

src/pages/MyPage/GroupInfo/GroupRequest.jsx
그룹 수락, 삭제시 request의 상태 재배열
요청 params user의 name 기준이 아니라 id 기준으로 수정
=> fix: 그룹요청 수락 삭제 오류 수정

src/pages/RankingPage/GroupRank/index.jsx, src/pages/RankingPage/UserRank/index.jsx, src/pages/RankingPage/index.jsx
=> fix: 랭킹 페이지 undefined 오류 수정

src/components/layout/Footer.jsx, src/components/layout/Main.jsx, src/components/layout/index.jsx
=> feat: 푸터 추가

src/components/common/Button.jsx, src/components/layout/Footer.jsx, src/components/layout/Header/index.jsx, src/components/layout/Header/style.module.css, src/components/layout/Main.jsx, src/components/layout/index.jsx, src/index.css, src/pages/CalendarPage/index.jsx, src/pages/DetailGroupPage/index.jsx, src/pages/MainPage/Notice.jsx, src/pages/MainPage/StudyGroup/index.jsx, src/pages/MainPage/index.jsx, src/pages/Notice/DetailNoticePage/index.jsx, src/pages/Notice/NoticePage/index.jsx, src/pages/RankingPage/GroupRank/index.jsx, src/pages/RankingPage/UserRank/index.jsx, src/pages/RankingPage/index.jsx, tailwind.config.js
- 필요없는 클래스명 제거
- 공통 CSS 처리
- UI 변경
=> refactor: 공통 로직 처리
